### ISSUE TITLE
Dockerize the Application

### ISSUE THREAD

**Issue by evrentan** [evrentan/qr-code-generator-backend#8]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Dockerize the Application.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ujwalkumar1995** [comment]
Hey @evrentan 
Do you want a multistage Dockerfile for this?
One that builds the application and then copies the generated app and exposes the port for the running application?

**Comment by mrbrianevans** [comment]
I can do this if you assign me. not sure if @ujwalkumar1995 was just commenting or is working on the issue?

**Comment by ujwalkumar1995** [comment]
@mrbrianevans 
Yeah I actually wanted to work on this. Just wanted to understand the requirement first.

**Comment by evrentan** [comment]
Thanks @ujwalkumar1995 & @mrbrianevans for your comments. I am assigning this to @ujwalkumar1995 and yes a multistage dockerfile will be perfect in order to optimize the final image and to maintain it.

**Comment by ujwalkumar1995** [comment]
Hey @evrentan 
While working on this issue, I am facing a problem while running the application in local. The problem seems to be related to lombok.
I have jdk 17 and gradle 7.3.2.
Same problem occurs when trying to create image from my Dockerfile. So it does not seem like a system specific issue.
Do you have any suggestion on why it may be happening?
I am looking into this meanwhile but would appreciate the help if you have any suggestions.
![Untitled](https://user-images.githubusercontent.com/20976813/197787113-29ac5f32-8643-41af-94f4-493daeb815a3.png)

**Comment by evrentan** [comment]
Hi @ujwalkumar1995,
Can you pull the latest main branch & retry? Thanks for informing.
